### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by tolstenko** [InfiniBrains/mobagen#40]
Allow Engine get and post data

**Comment by tolstenko** [comment]
As far as I know, the best option is libcurl and it depends on openssl. I am using HunterGate to deal with this kind of stuff.

**Comment by velrino** [comment]
![tenor](https://user-images.githubusercontent.com/8322467/40248040-f78b4062-5aa4-11e8-9906-e461a0b5a1f9.gif)

**Comment by tolstenko** [comment]
Fixed rest webrequest for win, linux and osx
